cloudflare_zone        = "asfasfsafsasfa.org"
gcp_billing_account_id = "019767-2A54C9-AE07C6"
# gcp_billing_account_name = "Los Verdes"
gcp_project_editors       = []
gcp_project_id            = "losverdesatx-events"
gcp_project_name          = "Los Verdes events page!"
gcp_project_owners        = ["Jeff.hogan1@gmail.com"]
gcp_region                = "us-central1"
gdrive_folder_name        = "lv-event-cover-images"
gdrive_settings_file_name = "event_page_settings.yaml"
github_repo               = "jeffwecan/lv-event-pagenerator"
page_description          = "Los Verdes Event Page"
source_calendar_id        = "information@losverdesatx.org"
static_site_hostname      = "los-verdes-events.asfasfsafsasfa.org"
